version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: 1 machine
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 1
          group: 1 machine
          spec: cypress/integration/activityHistoryPerson.feature