version: 2.1
parameters:
  run_workflow_ci:
    description: The default behaviour of the pipeline when a commit and/or merge is performed.
    default: true
    type: boolean

  run_workflow_GoogleLighthouse:
    default: false
    type: boolean

  run_workflow_accessibility_sequentially:
    default: false
    type: boolean

  external_trigger:
    description: Used to determine if the tests are triggered by a mfe upstream.
    default: false
    type: boolean

  external_pipeline:
    description: The name of the mfe that triggered the tests upstream.
    default: ""
    type: string

  target_environment:
    description: The target environment for the tests. Must be "development", "staging" or "production".
    default: "development"
    type: enum
    enum: ["development", "staging", "production"]

orbs:
  cypress: cypress-io/cypress@1
browsers-chrome78-ff70:
    docker:
      - image: cypress/browsers:node12.13.0-chrome78-ff70

jobs:
  trigger-recurring-pipeline:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: |
            curl --location --request POST 'https://circleci.com/api/v2/project/gh/LBHackney-IT/mtfh-frontend-<< pipeline.parameters.external_pipeline >>/pipeline' \
            --header 'Circle-Token: '"$CIRCLE_TOKEN"'' \
            --header 'Content-Type: application/json' \
            --data ' {"branch": "MTTL-856-configure-e2e-pipeline-trigger", "parameters": {"run-development-workflow": false, "run-temporary-workflow": true}}'

  trigger-accessibility:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: |
            curl --location --request POST 'https://circleci.com/api/v2/project/gh/LBHackney-IT/mtfh-tl-e2e-tests/pipeline' \
            --header 'Circle-Token: '"$CIRCLE_TOKEN"'' \
            --header 'Content-Type: application/json' \
            --data ' {"branch": "trigger_workflow_via_api", "parameters": {"run_workflow_ci": false, "run_workflow_GoogleLighthouse": true}}'
    
workflows:
  run-ci-tests:
    when: << pipeline.parameters.run_workflow_ci >>
    jobs:
      - cypress/run:
          name: ci
          command: export CYPRESS_ENVIRONMENT=<< pipeline.parameters.target_environment >>;
             echo $CYPRESS_ENVIRONMENT
             npm run test:cypress:run
          store_artifacts: true

  run-accessibility-tests:
    when: << pipeline.parameters.run_workflow_GoogleLighthouse >>
    jobs:
      - cypress/run:
          name: Google Lighthouse tests
          command: export CYPRESS_ENVIRONMENT=<< pipeline.parameters.target_environment >>;
             echo $CYPRESS_ENVIRONMENT
             npm run test:cypress:GoogleLighthouse
          store_artifacts: false
      
      - trigger-recurring-pipeline:
          requires:
            - Google Lighthouse tests

  run-cypress-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - cypress/run:
          name: chrome
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:chrome
          store_artifacts: true

      - cypress/run:
          name: electron
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:electron
          store_artifacts: true

      - cypress/run:
           name: firefox
           executor: cypress/browsers-chrome78-ff70
           command: npm run test:cypress:nightly:firefox
           store_artifacts: true
