version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  run-cypress-tests:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome67
          browser: chrome
          command: npx cypress run

