version: 2.1
orbs:
  cypress: cypress-io/cypress@1
browsers-chrome78-ff70:
    docker:
      - image: cypress/browsers:node12.13.0-chrome78-ff70
      - image: cypress/browsers:node14.10.1-edge88
workflows:
  run-ci-tests:
    jobs:
      - cypress/run:
          name: ci
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:nightly:edge
          store_artifacts: true
  run-cypress-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          name: chrome
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:firefox
          store_artifacts: true
      - cypress/run:
          name: edge
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:edge
          store_artifacts: true
      - cypress/run:
          name: electron
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:electron
          store_artifacts: true
      - cypress/run:
           name: firefox
           executor: cypress/browsers-chrome78-ff70
           command: npm run test:cypress:nightly:chrome
           store_artifacts: true
