version: 2.1
parameters:
  run_workflow_ci:
    default: true
    type: boolean

  run_workflow_GoogleLighthouse:
    default: false
    type: boolean
orbs:
  cypress: cypress-io/cypress@1
browsers-chrome78-ff70:
    docker:
      - image: cypress/browsers:node12.13.0-chrome78-ff70
workflows:
  run-ci-tests:
    when: << pipeline.parameters.run_workflow_ci >>
    jobs:
      - cypress/run:
          name: ci
          command: npm run test:cypress:run
          store_artifacts: true
  run-accessibility-tests:
    jobs:
      when: << pipeline.parameters.run_workflow_GoogleLighthouse >>
      - cypress/run:
          name: Google Lighthouse tests
          command: npm run test:cypress:GoogleLighthouse
          store_artifacts: false
  run-cypress-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          name: chrome
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:chrome
          store_artifacts: true
      - cypress/run:
          name: electron
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:electron
          store_artifacts: true
      - cypress/run:
           name: firefox
           executor: cypress/browsers-chrome78-ff70
           command: npm run test:cypress:nightly:firefox
           store_artifacts: true
