version: 2.1

parameters:
  run_workflow_ci:
    description: The default behaviour of the pipeline when a commit and/or merge is performed.
    default: true
    type: boolean

  external_pipeline:
    description: The name of the mfe that triggered the tests upstream.
    default: ""
    type: string

  external_trigger:
    description: Pipeline triggered externally
    default: false
    type: boolean

  development_environment:
    default: false
    type: boolean

  staging_environment:
    default: false
    type: boolean

  production_environment:
    default: false
    type: boolean
    
orbs:
  cypress: cypress-io/cypress@1
browsers-chrome78-ff70:
    docker:
      - image: cypress/browsers:node12.13.0-chrome78-ff70

jobs:
    run-e2e-tests:
        docker:
            - image: cypress/browsers:node12.13.0-chrome78-ff70
        steps:
            - when:
                condition: <<  pipeline.parameters.development_environment >>
                steps:
                  - run: export CYPRESS_ENVIRONMENT="development" ;
            - when:
                condition: <<  pipeline.parameters.staging_environment >>
                steps:
                  - run: export CYPRESS_ENVIRONMENT="staging" ;
            - when:
                condition: <<  pipeline.parameters.production_environment >>
                steps:
                  - run: export CYPRESS_ENVIRONMENT="production" ;
                run: npm run test:cypress:run
                
    trigger-downstream-deployment:
        docker:
          - image: cimg/base:2021.05
        steps:
          - when:
              condition: << pipeline.parameters.external_trigger >> 
              steps:
                - when:
                    condition: <<  pipeline.parameters.development_environment >>
                    steps:
                      - run: export TARGET_ENVIRONMENT="staging" ;
                - when:
                    condition: <<  pipeline.parameters.staging_environment >>
                    steps:
                      - run: export TARGET_ENVIRONMENT="production" ;             
                - run: |
                    echo "Deploying to $TARGET_ENVIRONMENT" ;
                    curl --location --request POST 'https://circleci.com/api/v2/project/gh/LBHackney-IT/mtfh-frontend-<< pipeline.parameters.external_pipeline >>/pipeline' \
                    --header 'Circle-Token: '"$CIRCLE_TOKEN"'' \
                    --header 'Content-Type: application/json' \
                    --data ' {"branch": "MTTL-856-configure-e2e-pipeline-trigger", "parameters": {"run-development-workflow": false, "run-temporary-workflow": true, "target_environment": '"$TARGET_ENVIRONMENT"'}}' ;

workflows:
  run-ci-tests:
    when: << pipeline.parameters.run_workflow_ci >>
    jobs:
      - cypress/run:
          name: ci
          command: export CYPRESS_ENVIRONMENT="development" ;
             echo "Running against $CYPRESS_ENVIRONMENT environment" ;
             npm run test:cypress:run
          store_artifacts: true

  trigger-e2e-tests:
    when: << pipeline.parameters.external_trigger >>
    jobs:
      - run-e2e-tests
      - trigger-downstream-deployment:
          requires: 
            - run-e2e-tests

  run-cypress-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - cypress/run:
          name: chrome
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:chrome
          store_artifacts: true

      - cypress/run:
          name: electron
          executor: cypress/browsers-chrome78-ff70
          command: npm run test:cypress:nightly:electron
          store_artifacts: true

      - cypress/run:
           name: firefox
           executor: cypress/browsers-chrome78-ff70
           command: npm run test:cypress:nightly:firefox
           store_artifacts: true

